return workflow result on submit
CermakM/argo-python-sdk pull request #16
Opened 2020-03-04 22:29 UTC by asavpatel92

Just to be consistent with `argo-client-python` returning `result --> V1alpha1Workflow` on workflow `submit()`

2020-03-08 07:21 UTC, CermakM requested changes
Thanks for the PR! Could you please TAL at the comments and do some quick fixes? :)

Cheers,
M

2020-03-08 07:21 UTC, CermakM commented on argo/workflows/dsl/_workflow.py
>          # return the computed Workflow ID
Remove the excessive `ID`

2020-03-08 07:21 UTC, CermakM commented on argo/workflows/dsl/_workflow.py
> +        return created
Fix the return type hint of the function and its docstring

2020-03-08 07:21 UTC, CermakM commented on tests/test_workflow.py
> +        assert workflow_result.metadata.name == "test"
As this is now a Workflow, we can check that the parameters are present and that its value indeed is `test` :grin:

2020-03-09 20:54 UTC, asavpatel92 commented
> Thanks for the PR! Could you please TAL at the comments and do some quick fixes? :)
> 
> Cheers,
> M

@CermakM done :-)

2020-03-12 13:00 UTC, CermakM commented
Thanks @asavpatel92 ! :+1: LGTM

2020-03-12 13:01 UTC, merged